#cloud-config

ssh_authorized_keys:
- "${ssh_key}"
config_system:
  configure: "true"
  hostname: mgmt-server
  mgmt_admin_name: "admin"
  mgmt_admin_passwd: "${pass}"
  mgmt_gui_clients_radio: any
  install_security_managment: "true"
  install_security_gw: "false"
  install_mgmt_primary: "true"
  install_mgmt_secondary: "false"
  download_info: "true"
  upload_info: "true"
  secondary: 77.88.8.8
  tertiary: 77.88.8.1
  ntp_primary: ntp1.yandex.net
  ntp_primary_version: 4
  ntp_secondary: ntp2.yandex.net
  ntp_secondary_version: 4