#cloud-config

blink_config:
  configure: "true"
  gateway_cluster_member: "false"
  download_info: "true"
  upload_info: "true"
  ftw_sic_key: "${pass_sic}"

ssh_authorized_keys:
- "${ssh_key}"

system:
  hostname: FW-B
  dns2: 77.88.8.8
  dns3: 77.88.8.1
  ntp1:
    address: ntp1.yandex.net
    version: 4
  ntp2:
    address: ntp2.yandex.net
    version: 4

routing:
  static:
%{ for dst, next-hop in static-routes }
    - dst: "${dst}"
      nexthop: "${next-hop}"
%{ endfor ~}

clishcmd:
- 'set static-route default nexthop gateway address "${gw}" on'
- 'set static-route default nexthop gateway address 192.168.2.1 off'
- 'save config'